pre-commit check for TABs

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -44,6 +44,14 @@ If you know what you are doing you can disable this check using:
 EOF
     exit 1
 fi
+
+# Check for tabs.
+if
+    git diff --cached --name-only | grep -P '\.(tex|bib)$' | \
+    xargs git diff --cached | grep -P '\t'
+then
+    echo "ABORT: Tabs found in commit to .tex or .bib files."
+    exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
